server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    #zookeeper配置
    zookeeper:
      #连接地址
      #connect-string: 112.126.59.115:2182,112.126.59.115:2181
      connect-string: 112.126.59.115:2181
