server:
  port: 8005

spring:
  application:
    name: cloud-payment-service
  cloud:
    #consul配置
    consul:
      #ip
      host: 112.126.59.115
      #host: localhost
      #端口
      port: 8500
      #服务发现
      discovery:
        #服务名
        service-name: ${spring.application.name}
        hostname: 127.0.0.1