server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-service
  zipkin:
    base-url: http://112.126.59.115:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  #开启hystrix的支持
  hystrix:
    enabled: true
