server:
  port: 8006

spring:
  application:
    name: cloud-payment-service

  cloud:
    consul:
      host: 112.126.59.115
     # host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 127.0.0.1
